config/routes.rb
Rails.application.routes.draw do
  get 'robot/index'

  get 'robot/place'
  get 'robot/place/:x/:y' => 'robot#place', as: 'robot_place_x_y'

  get 'robot/move'

  get 'robot/left'

  get 'robot/right'

  get 'robot/report'

  root to: 'robot#index', as: 'root_path'

end

app/models/robot.rb
class Robot < ActiveRecord::Base
  FACING = [ North = 0, East = 1, South = 2, West = 3 ]

  attr_reader :xbounds, :ybounds

  after_initialize :default_values

  def place x, y, f
    unless x >= @xbounds || y >= @ybounds || !FACING[f]
      self.pos_x = x
      self.pos_y = y
      self.facing = f

      true
    else
      false      
    end
  end

  def move?
    if self.facing === North && self.pos_y < @ybounds - 1
      # puts 'Moving north'
      self.pos_y += 1
    elsif self.facing === East && self.pos_x < @xbounds - 1
      # puts 'Moving east'
      self.pos_x += 1
    elsif self.facing === South && self.pos_y > 0
      # puts 'Moving south'
      self.pos_y -= 1
    elsif self.facing === West && self.pos_x > 0
      # puts 'Moving west'
      self.pos_x -= 1
        
    else
      puts 'No moving possible!'

      false
    end
  end

  def left?
    turn? -1
  end

  def right?
    turn? 1
  end

  def report
    rep = "Current position:\n  x = #{self.pos_x};\n  y = #{self.pos_y},\n  heading: #{get_direction}"
    # puts rep
    rep
  end

  def get_direction
    Robot.constants.find{ |name| Robot.const_get(name) == self.facing }
  end

private

  def default_values
    @xbounds = 5
    @ybounds = 5
  end

  def turn? steps
    self.facing = ( self.facing + steps ) % 4
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/robot_controller.rb
class RobotController < ApplicationController
  before_action :set_robot
  before_action :validate_placement

  def index
  end

  def place
    @robot.place (params[:x] || 0), (params[:y] || 0), Robot::North
    @robot.save
    
    forward_to_view
  end

  def move
    if @robot.move?
      @robot.save
    else
      flash[:danger] = "Couldn't move!"
    end

    forward_to_view
  end

  def left
    @robot.left?
    @robot.save
    
    forward_to_view
  end

  def right
    @robot.right?
    @robot.save
    
    forward_to_view
  end

  def report
    flash[:success] = @robot.report

    forward_to_view
  end

private

  def set_robot
    @robot = Robot.find(session[:robot])
  rescue ActiveRecord::RecordNotFound
    @robot ||= Robot.create

    session[:robot] = @robot.id
  end

  def validate_placement
    params[:x] = params[:x].to_i
    params[:y] = params[:y].to_i
  end

  def forward_to_view
    respond_to do |format|
      format.html { redirect_to robot_index_path }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/robot_helper.rb
module RobotHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Robot Toy</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/robot/index.html.erb
    <div class="row">
      <div class="col-md-12">
        <h1>Robot Toy</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <% (@robot.ybounds - 1).downto(0) do |i| %>
          <div class="field-row">
            <% for j in 0..(@robot.xbounds - 1) do %>
            <div id="field-<%= "#{i}-#{j}" %>" class="field" style="width:<%= 99/@robot.xbounds %>%;">
              <%= link_to robot_place_x_y_path( x: j,y: i ), class: "field-inner" do %>
                <span><%= "#{j}x#{i}" %></span>
                <% if @robot.pos_x == j && @robot.pos_y == i %>
                <div>
                  <i class="fa fa-caret-square-o-up <%= "fa-rotate-" + (@robot.facing * 90 % 360).to_s %>"></i>
                </div>
                <% end %>
              <% end %>
            </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="col-md-6 col-sm-12 control">
        <p><%= link_to robot_place_path, class: "btn btn-lg btn-primary" do %>
          Place 0x0 <i class="fa fa-dot-circle-o"></i>
        <% end %></p>
        <p><%= link_to robot_move_path, class: "btn btn-lg btn-primary" do  %>
          Move <i class="fa fa-arrow-up"></i>
        <% end %></p>
        <p><%= link_to robot_left_path, class: "btn btn-lg btn-primary" do  %>
          Left <i class="fa fa-reply"></i>
        <% end %></p>
        <p><%= link_to robot_right_path, class: "btn btn-lg btn-primary" do  %>
          Right <i class="fa fa-reply fa-flip-horizontal"></i>
        <% end %></p>
        <p><%= link_to robot_report_path, class: "btn btn-lg btn-primary" do  %>
          Report <i class="fa fa-file-text-o"></i>
        <% end %></p>

        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: ["alert-" + name, "alert"] %>
        <% end %>
      </div>
    </div>